In [5]:
import numpy as np

arr = np.random.randint(1, 31, (5, 3))
print(arr,"\n")

arr = arr.T
print(arr,"\n")

arr1 = arr[:, 1:4]
print(arr1,"\n")

arr.sort(0)
print(arr1,"\n")

arr1.mean(axis=0)

[[16 24 29]
 [15 10  7]
 [25  6 12]
 [11  4 23]
 [15  3  2]] 

[[16 15 25 11 15]
 [24 10  6  4  3]
 [29  7 12 23  2]] 

[[15 25 11]
 [10  6  4]
 [ 7 12 23]] 

[[ 7  6  4]
 [10 12 11]
 [15 25 23]] 



array([10.66666667, 14.33333333, 12.66666667])