In [1]:
# ★の部分をかいて完成させてね
import cv2
import numpy as np

try:
    img = cv2.imread('hoge.jpg')

    if img is None:
        print ('ファイルを読み込めません。')
        import sys

    cv2.imshow('img', img)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
except:
    import sys
    print("Error:", sys.exc_info()[0])
    print(sys.exc_info()[1])
    import traceback
    print(traceback.format_tb(sys.exc_info()[2]))

In [2]:
# ★の部分をかいて完成させてね
import cv2
import numpy as np

try:
    img = cv2.imread('hoge.jpg')

    if img is None:
        print ('ファイルを読み込めません。')
        import sys
    
    img_array = np.asarray(img)
    h, w, _ = img.shape

    np.random.seed(0)
    data1 = np.random.randint(0,h, 100000)
    data2 = np.random.randint(0,w, 100000)
    
    img[(data1,data2)] = (0,0,0)
    
    cv2.imshow('dst',img)
    
    cv2.imwrite('hogegray.jpg', img)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
except:
    import sys
    print("Error:", sys.exc_info()[0])
    print(sys.exc_info()[1])
    import traceback
    print(traceback.format_tb(sys.exc_info()[2]))

In [19]:
# writerow()やwriterows()を使って、九九表をganbare.csvに出力してみてね
#printしたときに、変な空行が入らないようにしてね！

'''
出力例
[1,2,...,8,9]
[2,4,...,16,18]
...
[8,16,...,64,72]
[9,18,...,72,81]
'''

import csv


# ここにかいてね
import numpy as np

ganbare=np.empty([9,9], dtype='int')

for i in range(1,10):
    for y in range(1,10):
        ganbare[i-1][y-1]=str(i*y)
        
g = open("ganbare.csv", "w",newline="")
w = csv.writer(g)
w.writerows(ganbare)
g.close()

with open('ganbare.csv') as f:
    reader = csv.reader(f)
    l = [row for row in reader]
    for r in l:
        print(r)

['1', '2', '3', '4', '5', '6', '7', '8', '9']
['2', '4', '6', '8', '10', '12', '14', '16', '18']
['3', '6', '9', '12', '15', '18', '21', '24', '27']
['4', '8', '12', '16', '20', '24', '28', '32', '36']
['5', '10', '15', '20', '25', '30', '35', '40', '45']
['6', '12', '18', '24', '30', '36', '42', '48', '54']
['7', '14', '21', '28', '35', '42', '49', '56', '63']
['8', '16', '24', '32', '40', '48', '56', '64', '72']
['9', '18', '27', '36', '45', '54', '63', '72', '81']


In [22]:
#numpyの二次元配列cを左右反転して、全部５倍にしてね
# 二行が理想、importより下３行が理解できたらめっちゃいい
'''
例
c= [[1,2,3]
    [4,5,6]
    [7,8,9]]
なら
res=[[15,10,5]
    [30,25,20]
    [45,40,35]]
'''
import numpy as np
a=np.array([1,2,3,4,5])
a=a.reshape([5,1])
b=-np.array([1,2,3,4,5])

print("-----a------")
print(a)

print("-----b------")
print(b)

c=a+b
print("-----c------")
print(c)

# ここにかいてね
res=np.flip(c*5,axis=1)
print("-----出力-----")
print(res)

-----a------
[[1]
 [2]
 [3]
 [4]
 [5]]
-----b------
[-1 -2 -3 -4 -5]
-----c------
[[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 4  3  2  1  0]]
-----出力-----
[[-20 -15 -10  -5   0]
 [-15 -10  -5   0   5]
 [-10  -5   0   5  10]
 [ -5   0   5  10  15]
 [  0   5  10  15  20]]


In [21]:
#問題１をnumpyを使ってやってみてね
#ファイル名はganbare2.csvにしてね
#すでにnumpyでやってたそこの君はコピペでおっけー
import csv
import numpy as np

#ここにかいてね
ganbare2=np.empty([9,9], dtype='int')

for i in range(1,10):
    for y in range(1,10):
        ganbare2[i-1][y-1]=str(i*y)
        
g = open("ganbare2.csv", "w",newline="")
w = csv.writer(g)
w.writerows(ganbare2)
g.close()


with open('ganbare2.csv') as f:
    print(f.read())

1,2,3,4,5,6,7,8,9
2,4,6,8,10,12,14,16,18
3,6,9,12,15,18,21,24,27
4,8,12,16,20,24,28,32,36
5,10,15,20,25,30,35,40,45
6,12,18,24,30,36,42,48,54
7,14,21,28,35,42,49,56,63
8,16,24,32,40,48,56,64,72
9,18,27,36,45,54,63,72,81

