# ⑧（ファイルと例外処理）

# Lesson10

### Sample1.py

In [1]:
f = open("Sample.txt", "w")

f.write("こんにちは\n")
f.write("さようなら\n")

f.close()

### with文
```Python
with <処理> as <ファイル変数>:
```

### Sample2.py

In [2]:
f = open("Sample.txt", "r")

lines = f.readlines()

for line in lines:
    print(line, end="")

f.close()

こんにちは
さようなら


### 構文（csvモジュールの利用）
```Python
import csv
```

### Sample3.py

In [3]:
import csv

f = open("Sample.csv", "r")

rd = csv.reader(f)

for row in rd:
    for col in row:
       print(col, end=",")
    print()
f.close()

東京,鉛筆,25,
東京,消しゴム,30,
名古屋,ノート,56,
大阪,定規,100,
福岡,ノート,73,



### 構文（jsonモジュールの利用）
```Python
import json
```

### Sample4.py

In [4]:
import json

f = open("Sample.json", "r")

data = json.load(f)

print(data)

f.close()

{'関東': {'東京': 50, '横浜': 40}, '関西': {'大阪': 30, '京都': 20}}


### 構文（例外処理）
```Python
try:
    <例外発生を調べる文>
    ・・・
except <例外クラス名>:
    <例外が起きた時に処理する文>
    ・・・
else:
    <例外が起きなかった時に処理する文>
    ・・・
finally:
    <必ず最後に処理する文>
    ・・・
```

### Sample5.py

In [5]:
try:
    f = open("Sample.txt", "r")
   
except FileNotFoundError:
    print("ファイルをオープンできませんでした。")

else:
    lines = f.readlines()
    for line in lines:
       print(line, end="")
    f.close()

finally:
    print("処理を終了します。")

こんにちは
さようなら
処理を終了します。


## osモジュール関連の話
https://techacademy.jp/magazine/31132

### 構文（osモジュールの利用）
```Python
import os
```

### Sample6.py

In [6]:
import os

curdir = os.listdir(".")

for name in curdir:
    print(name)

.ipynb_checkpoints
Sample.csv
Sample.json
Sample.txt
Sample1.py
Sample2.py
Sample3.py
Sample4.py
Sample5.py
Sample6.py
Sample7.py
Sample8.py
Sample9.py
⑧（ファイルと例外処理）.html
⑧（ファイルと例外処理）.ipynb
エクストラ問題倉庫


### 構文（os.pathモジュールの利用）
```Python
import os.path
```

### Sample7.py

In [7]:
import os
import os.path

curdir = os.listdir(".")

for name in curdir:
    print(os.path.abspath(name), end=",")
    
    if(os.path.isfile(name)):
        print("ファイルです。")
    else:
        print("ディレクトリです。")
print()

C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\.ipynb_checkpoints,ディレクトリです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample.csv,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample.json,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample.txt,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample1.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample2.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample3.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample4.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample5.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample6.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample7.py,ファイルです。
C:\Users\kng-kudo\Desktop\AI\Freshman\AIプログラミングⅠ\⑧（ファイルと例外処理）\Sample8.py,ファイルです。
C:\Users\kng-kudo

### 構文（日時情報の利用）
```Python
import datetime
```

### Sample8.py

In [8]:
import datetime

dt = datetime.datetime.now()
print("現在は", dt, "です。")
print("年：", dt.year)
print("月：", dt.month)
print("日：", dt.day)

dt = dt + datetime.timedelta(days=1)
print("1日後は", dt, "です。")

現在は 2020-08-05 11:53:59.451434 です。
年： 2020
月： 8
日： 5
1日後は 2020-08-06 11:53:59.451434 です。


### Sample9.py

In [9]:
import datetime

dt = datetime.datetime.now()
str = dt.strftime("%c")
print("現在は", str, "です。")

dt = dt + datetime.timedelta(days=1)
str = dt.strftime("%Y-%m-%d")
print("1日後は", str, "です。")

現在は Wed Aug  5 11:54:00 2020 です。
1日後は 2020-08-06 です。


# ほげ要望(^ω^)
　教科書　【レッスンのまとめ】    
・lesson10  
 練習をやってくれたら喜びます

# エクストラほげ問題⑧
## 高校数学Ⅱ　複素数と方程式
## 複素数の四則計算
人工知能（AI）を学ぶ上で必須な数学の知識を問うような問題を出します。  
最低限の内容ばかり問うのでわからない人は焦った方がいいと思います（ほげおくん調べ）  
  
### もんだいだよん(^ω^)
 
計算せよ
  
①$(2-i)^3$
  
②$i+i^2+i^3+i^4+…+i^{50}$
  
③$(\sqrt{3}+\sqrt{-2})(\sqrt{-6}-\sqrt{4})$
  
④$\frac{1+i}{3-2i}+\frac{1-3i}{1+2i}$

## エクストラぽむぽむ問題

## 画像ファイルを開いてみよう
>Wordとかのファイルも開けるんだから、画像ファイルだって開けます。

opencvというライブラリで画像を読み込んでみよう。
<br>このnotebookと同じ場所にimgファイルを作り、その中に任意の画像(jpg)をhogeとして１枚保存してね。

##### インポートエラーに気を付けてね　わからなかったら聞いてください

#### 実行すると画面に保存した画像が出てきます。てきとうに任意のキーボードを押すと消えます。

In [ ]:
# ★の部分をかいて完成させてね
import cv2
import numpy as np

try:
    img = #★　画像読み込み部分

    if img is None:
        print ('ファイルを読み込めません。')
        import sys

    cv2.imshow('img', img)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
except:
    import sys
    print("Error:", sys.exc_info()[0])
    print(sys.exc_info()[1])
    import traceback
    print(traceback.format_tb(sys.exc_info()[2]))


### 2.画像ファイルの保存
>保存が正しくできたら見てみてね。なんでそうなったか気になったら調べてみるといいかも。

読み込めたので、次は保存してみます。
保存の場所はさっき作ったimgフォルダで、hogegray.jpgという形式で保存してください。
#### 正しく実行するとimgフォルダにhogegray.jpgという画像ができています。確認してね

In [ ]:
# ★の部分をかいて完成させてね
import cv2
import numpy as np

try:
    img = #★　imgファイル内のhoge.jpgを読み込み

    if img is None:
        print ('ファイルを読み込めません。')
        import sys
    
    img_array = np.asarray(img)
    h, w, _ = img.shape

    np.random.seed(0)
    data1 = np.random.randint(0,h, 100000)
    data2 = np.random.randint(0,w, 100000)
    
    img[(data1,data2)] = (0,0,0)
    
    cv2.imshow('dst',img)
    
    #★　imgフォルダ内にhogegray.jpgとして保存
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
except:
    import sys
    print("Error:", sys.exc_info()[0])
    print(sys.exc_info()[1])
    import traceback
    print(traceback.format_tb(sys.exc_info()[2]))


# エクストラがんばれもんだい
がんばれー
つぎDBなんだけど使うときやればいいと思うのでnumpyやろうね

In [39]:
# writerow()やwriterows()を使って、九九表をganbare.csvに出力してみてね
#printしたときに、変な空行が入らないようにしてね！

'''
出力例
[1,2,...,8,9]
[2,4,...,16,18]
...
[8,16,...,64,72]
[9,18,...,72,81]
'''

import csv


# ここにかいてね



with open('ganbare.csv') as f:
    reader = csv.reader(f)
    l = [row for row in reader]
    for r in l:
        print(r)

In [14]:
#numpyの二次元配列cを左右反転して、全部５倍にしてね
# 二行が理想、importより下３行が理解できたらめっちゃいい
'''
例
c= [[1,2,3]
    [4,5,6]
    [7,8,9]]
なら
res=[[15,10,5]
    [30,25,20]
    [45,40,35]]
'''
import numpy as np
a=np.array([1,2,3,4,5])
a=a.reshape([5,1])
b=-np.array([1,2,3,4,5])

print("-----a------")
print(a)

print("-----b------")
print(b)

c=a+b
print("-----c------")
print(c)

# ここにかいてね
res=c
print("-----出力-----")
print(res)

-----a------
[[1]
 [2]
 [3]
 [4]
 [5]]
-----b------
[-1 -2 -3 -4 -5]
-----c------
[[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 4  3  2  1  0]]
-----出力-----
[[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 4  3  2  1  0]]


In [37]:
#問題１をnumpyを使ってやってみてね
#ファイル名はganbare2.csvにしてね
#すでにnumpyでやってたそこの君はコピペでおっけー
import csv
import numpy as np

#ここにかいてね



with open('ganbare2.csv') as f:
    print(f.read())

[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
1,2,3,4,5,6,7,8,9

2,4,6,8,10,12,14,16,18

3,6,9,12,15,18,21,24,27

4,8,12,16,20,24,28,32,36

5,10,15,20,25,30,35,40,45

6,12,18,24,30,36,42,48,54

7,14,21,28,35,42,49,56,63

8,16,24,32,40,48,56,64,72

9,18,27,36,45,54,63,72,81


